INSERT OR REPLACE INTO case_studies (
  id, slug, client_name, client_name_en, client_logo, service_type,
  challenge_ar, challenge_en, solution_ar, solution_en,
  results_ar, results_en, metrics_json, cover_image,
  testimonial_ar, testimonial_en, testimonial_author,
  is_published, created_at
) VALUES 
(
  1,
  'nh-clinics',
  'عيادات NH',
  'NH Clinics',
  'assets/logos/clients/client-05-nh-clinics.webp',
  'Social Media',
  'كانت العيادات بحاجة لزيادة الحجوزات والوصول إلى فئات جديدة في القاهرة الكبرى',
  'They needed to increase bookings and reach new demographics across Greater Cairo',
  'قمنا ببناء استراتيجية سوشيال ميديا متكاملة مع إنتاج فيديوهات Reels طبية توعوية جذابة وحملات ميديا باينج دقيقة',
  'We built an integrated social media strategy with educational clinical Reels and precision targeting',
  'تحقيق نمو بنسبة 250% في الحجوزات ومضاعفة التفاعل العضوي',
  '250% increase in patient bookings and doubled organic engagement',
  '[{"label":"الحجوزات","value":"+250%"},{"label":"التفاعل","value":"+180%"},{"label":"الوصول","value":"1.2M+"}]',
  'assets/images/hero-statue.webp',
  'شغل احترافي جداً والتزام تام بالنتائج والمواعيد',
  'Very professional work with exceptional commitment to milestones',
  'د. أحمد منصور — مدير مراكز NH Clinics',
  1,
  datetime('now')
),
(
  2,
  'island-gym',
  'Island Gym',
  'Island Gym',
  'assets/logos/clients/client-14-island-gym.webp',
  'Media Buying',
  'كانت الميزانية الإعلانية تُنفق دون تحقيق عائد استثمار واضح أو اشتراكات جديدة',
  'Ad budget was previously spent without clear conversion tracking or new memberships',
  'أعدنا هيكلة الحساب الإعلاني واستهدفنا الرياضيين المحليين بإعلانات فيديو سينمائية وعروض اشتراك مخصصة',
  'We restructured their ad accounts with localized high-converting video ads and targeted membership tiers',
  'انخفاض تكلفة الاستحواذ بنسبة 45% وتحقيق عائد إعلاني 4.2x',
  '45% lower CPA and achieved 4.2x ROAS',
  '[{"label":"توفير CPA","value":"-45%"},{"label":"العائد ROAS","value":"4.2x"},{"label":"مشتركون جدد","value":"+620"}]',
  'assets/images/hero-statue.webp',
  'أفضل استثمار إعلاني قمنا به منذ تأسيس النادي',
  'Best marketing decision and ROI since we launched our gym',
  'كابتن عمر زكي — المدير التنفيذي',
  1,
  datetime('now')
);
