name = "pragency"
compatibility_date = "2024-11-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "2d-marketing-db"
database_id = "7f2ae756-a713-4936-94fb-b8b2b05f6878"

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "pragency-analytics"
database_id = "9948c70f-d00f-4af8-8f39-8ae205b23281"

[vars]
TELEGRAM_BOT_TOKEN = "8857951958:AAGLCjUIW_KwZZ-Tl07LfKEvhw5XsC-bp7s"
TELEGRAM_CHAT_ID = "5715939844"
NOTIFY_COUNTRIES = "EG,SA,AE"

[ai]
binding = "AI"


